name: Build PR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Chrome OS environment
        run: |
          ./deps
          cd kernel
          export CHROMEOS_KERNEL_FAMILY=termina
      - name: Prepare kernel configuration
        run: make olddefconfig

      - name: Build kernel image
        run: make -j$(nproc) bzImage
  build_pages:
    runs-on: ubuntu-latest
    container:
      image: debian:latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Setup okLinux environment
        run: |
          ./deps
          /usr/bin/python3 -m venv sphinx
          . sphinx/bin/activate
          pip install -r ./Documentation/sphinx/requirements.txt
      - name: Make htmldocs
        run: make htmldocs