
name: Build Kernel Image
on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Chrome OS environment
        run: |
          ./deps
          cd kernel
          export CHROMEOS_KERNEL_FAMILY=termina
          

      - name: Prepare kernel configuration
        run: make olddefconfig

      - name: Build kernel image
        run: make -j$(nproc) bzImage
