
name: Build Kernel Image
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up okLinux environment
        if: ${{ steps.release.outputs.release_created }}  
        run: |
          ./deps
          cd kernel
          export CHROMEOS_KERNEL_FAMILY=termina
      - name: Prepare kernel configuration
        run: make olddefconfig
      - name: Build kernel image
        run: make -j$(nproc) bzImage
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64
          path: arch/x86_64
