name: publish

on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Set up Chrome OS environment
        if: ${{ steps.release.outputs.release_created }}  
        run: |
          ./deps
          cd kernel
          export CHROMEOS_KERNEL_FAMILY=termina
      - name: Prepare kernel configuration
        if: ${{ steps.release.outputs.release_created }}  
        run: make olddefconfig
      - name: Build kernel image
        if: ${{ steps.release.outputs.release_created }}  
        run: make -j$(nproc) bzImage
      - name: Upload Release Artifact  
        if: ${{ steps.release.outputs.release_created }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./arch/x86_64/boot/bzImage
